// Generated output: app/src/generated/contracts.ts
// Reads Foundry build artifacts and emits TypeScript as-const literals so viem
// gets full literal-type inference (JSON.parse would widen to Abi and lose types).
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))

const outDir = resolve(__dirname, '../../contracts/out')

function readAbi(contractFile, contractName) {
  const artifactPath = resolve(outDir, contractFile, `${contractName}.json`)
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'))
  return artifact.abi
}

const factoryAbi = readAbi('PontiFactory.sol', 'PontiFactory')
const groupAbi   = readAbi('PontiGroup.sol',   'PontiGroup')

const header = `\
// Generated by scripts/gen-abi.mjs. Do not hand-edit.
// Rerun \`pnpm gen:abi\` after any contract change.
`

const content = `${header}
export const factoryAbi = ${JSON.stringify(factoryAbi, null, 2)} as const

export const groupAbi = ${JSON.stringify(groupAbi, null, 2)} as const
`

const outFile = resolve(__dirname, '../src/generated/contracts.ts')
mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, content, 'utf8')

console.log('gen-abi: wrote', outFile)
